pipeline {
    agent any

    environment {
        SONAR_URL = 'http://localhost:9000'
        NEXUS_URL = 'http://localhost:8081/repository/java-repo/'
        NEXUS_SETTINGS_ID = 'd2093c9d-1921-46ce-bc0e-5c19c03900ad'
        AWS_ACCOUNT_ID = 'YOUR_ACCOUNT_ID'
        AWS_REGION = 'us-east-1'
        ECR_REPOSITORY = 'YOUR_ECR_REPOSITORY'
    }

    triggers {
        githubPush()
    }

    stages {

        stage('Build') {
            steps {
                dir('spring-boot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube') {
            steps {
                dir('spring-boot-app') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            mvn sonar:sonar \
                              -Dsonar.projectKey=spring-boot-demo \
                              -Dsonar.projectName=spring-boot-demo \
                              -Dsonar.host.url=$SONAR_URL \
                              -Dsonar.token=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }

        stage('Nexus Upload') {
            steps {
                dir('spring-boot-app') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'nexus-cred',
                            usernameVariable: 'NEXUS_USER',
                            passwordVariable: 'NEXUS_PASS'
                        )
                    ]) {
                        configFileProvider([
                            configFile(
                                fileId: "${NEXUS_SETTINGS_ID}",
                                variable: 'MAVEN_SETTINGS'
                            )
                        ]) {
                            sh '''
                                mvn deploy -DskipTests \
                                    --settings $MAVEN_SETTINGS \
                                    -DaltDeploymentRepository=nexus::default::$NEXUS_URL
                            '''
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('spring-boot-app') {
                    sh '''
                        docker build \
                        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$BUILD_NUMBER .
                    '''
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$BUILD_NUMBER
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-cred'
                    ]
                ]) {
                    sh '''
                        aws ecr get-login-password --region $AWS_REGION | \
                        docker login --username AWS --password-stdin \
                        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

                        docker push \
                        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$BUILD_NUMBER
                    '''
                }
            }
        }
    }

    post {
        failure {
            mail to: 'your-real-email@gmail.com',
                 subject: "Pipeline Failed: ${currentBuild.fullDisplayName}",
                 body: "Build failed. Check console output at ${env.BUILD_URL}"
        }
    }
}